# Generated by Django 4.0.3 on 2022-03-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseManagement', '0002_application_renter_application_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='application',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='unit_lease',
            name='application',
        ),
        migrations.RemoveField(
            model_name='unit_lease',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
