# Generated by Django 4.0.3 on 2022-03-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseManagement', '0004_application_unit_unit_lease_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='renter',
        ),
        migrations.RemoveField(
            model_name='application',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='unit_lease',
            name='application',
        ),
        migrations.RemoveField(
            model_name='unit_lease',
            name='unit',
        ),
    ]
