# Generated by Django 4.0.3 on 2022-03-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rent_payment_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('payment_medium', models.TextField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('check_number', models.IntegerField(null=True)),
                ('online_transaction_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_description', models.TextField()),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('closure_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('staff_role', models.CharField(max_length=50)),
                ('staff_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
