# Generated by Django 4.0.3 on 2022-03-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffManagement', '0002_rent_payment_log_staff_rent_payment_log_unit_lease_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent_payment_log',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='rent_payment_log',
            name='unit_lease',
        ),
        migrations.RemoveField(
            model_name='service_request',
            name='Service_Category',
        ),
        migrations.RemoveField(
            model_name='service_request',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='service_request',
            name='unit_lease',
        ),
    ]
